#ifndef _XENO_MENU_RESOURCES_H
#define _XENO_MENU_RESOURCES_H

#define MENU_RESOURCE_NONE 0xFFFF

#define MENU_TEX_STRING_ATTACK 0xDE

#define MENU_TEX_STRING_DEFENSE 0xE0

#define MENU_TEX_PLUS 0xE3

#define MENU_TEX_MINUS 0xE5

// The "- <==> +" graphics used in shop windows to explain quantities
#define MENU_TEX_QUANTITY_EXPLANATION 0xF2

#define MENU_TEX_WINDOW_BORDER_TOP_LEFT 0xFD
#define MENU_TEX_WINDOW_BORDER_TOP 0xFE
#define MENU_TEX_WINDOW_BORDER_TOP_RIGHT 0xFF
#define MENU_TEX_WINDOW_BORDER_LEFT 0x100
#define MENU_TEX_WINDOW_BORDER_RIGHT 0x101
#define MENU_TEX_WINDOW_BORDER_BOTTOM_LEFT 0x102
#define MENU_TEX_WINDOW_BORDER_BOTTOM 0x103
#define MENU_TEX_WINDOW_BORDER_BOTTOM_RIGHT 0x104

#define MENU_TEX_SCROLL_BAR_ORNAMENT 0x105
#define MENU_TEX_SCROLL_BAR_EMPTY 0x106
#define MENU_TEX_SCROLL_BAR_HANDLE 0x107

#define MENU_TEX_POINTER_CURSOR 0x108

// These are all the same ball cursor texture, the only difference
// is their position on the screen
#define MENU_TEX_BALL_CURSOR_1 0x109
#define MENU_TEX_BALL_CURSOR_2 0x10A
#define MENU_TEX_BALL_CURSOR_3 0x10B
#define MENU_TEX_BALL_CURSOR_4 0x10C
#define MENU_TEX_BALL_CURSOR_5 0x10D
#define MENU_TEX_BALL_CURSOR_6 0x10E
#define MENU_TEX_BALL_CURSOR_7 0x10F
#define MENU_TEX_BALL_CURSOR_8 0x110
#define MENU_TEX_BALL_CURSOR_9 0x111
#define MENU_TEX_BALL_CURSOR_10 0x112
#define MENU_TEX_BALL_CURSOR_11 0x113
#define MENU_TEX_BALL_CURSOR_12 0x114
#define MENU_TEX_BALL_CURSOR_13 0x115
#define MENU_TEX_BALL_CURSOR_1_ACTIVE 0x109 + 0xD
#define MENU_TEX_BALL_CURSOR_2_ACTIVE 0x10A + 0xD
#define MENU_TEX_BALL_CURSOR_3_ACTIVE 0x10B + 0xD
// ... 0x121

#define MENU_TEX_STRING_FILE 0x130
// #define MENU_TEX_STRING_EXIT 0x131 - Same as 0x137, different position
#define MENU_TEX_STRING_SKILLS 0x132
#define MENU_TEX_STRING_ABILITIES 0x133
#define MENU_TEX_STRING_EQUIP 0x134
#define MENU_TEX_STRING_BUY 0x135
#define MENU_TEX_STRING_SELL 0x136
#define MENU_TEX_STRING_EXIT 0x137
#define MENU_TEX_STRING_ITEMS 0x138
// #define MENU_TEX_WEAPONS 0x139 - Same 0x144, but differently positioned
#define MENU_TEX_STEREO 0x140
#define MENU_TEX_WIDE_STEREO 0x141
#define MENU_TEX_MONO 0x142
#define MENU_TEX_STRING_TUNE_UP 0x143
#define MENU_TEX_STRING_WEAPONS 0x144
#define MENU_TEX_STRING_PARTS 0x145
#define MENU_TEX_STRING_FUEL 0x146
#define MENU_TEX_STRING_ENGINE 0x147
#define MENU_TEX_STRING_FRAME 0x148
#define MENU_TEX_STRING_ARMOR 0x149

#define MENU_TEX_CHARACTER_PORTRAITS_SMALL 0x14E
#define MENU_TEX_FEI_PORTRAIT_SMALL 0x14E
#define MENU_TEX_ELLY_PORTRAIT_SMALL 0x14F
#define MENU_TEX_CITAN_PORTRAIT_SMALL 0x150
#define MENU_TEX_BART_PORTRAIT_SMALL 0x151
#define MENU_TEX_BILLY_PORTRAIT_SMALL 0x152
#define MENU_TEX_RICO_PORTRAIT_SMALL 0x153
#define MENU_TEX_EMERALDA_YOUNG_PORTRAIT_SMALL 0x154
#define MENU_TEX_CHU_CHU_PORTRAIT_SMALL 0x155
#define MENU_TEX_MARIA_PORTRAIT_SMALL 0x156
#define MENU_TEX_UNUSED_PORTRAIT_SMALL 0x157 // Possibly intended for Margie?
#define MENU_TEX_EMERALDA_ADULT_PORTRAIT_SMALL 0x158

// Start of arrow cursor frames, 5 frames total: 0x15B, 0x15C, 0x15D, 0x15E, 0x15F
#define MENU_TEX_ARROW_CURSOR 0x15B

#define MENU_TEX_L1_RED_ARROW 0x164
#define MENU_TEX_R1_RED_ARROW 0x165

#endif
